twig:
    file_name_pattern: '*.twig' 
#    Définir une variable globale twig pour afficher toutes les catgories dans base.html.twig
    globals:
        categories: '@App\Repository\CategoriesRepository'

when@test:
    twig:
        strict_variables: true


